# Generated by Django 5.2.6 on 2025-09-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('LINK', 'Link sharing'), ('VISIT', 'Visit with footer code'), ('SEARCH', 'Google search + visit'), ('MAPS', 'Google Maps task')], default='VISIT', max_length=12)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reward_currency', models.CharField(default='USDT', max_length=24)),
                ('reward_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('quota_total', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('client_site_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('secret_code', models.CharField(blank=True, help_text='If all users read the same footer code, put it here.', max_length=120, null=True)),
                ('code_case_sensitive', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('nonce', models.CharField(blank=True, max_length=64, null=True)),
                ('wallet_solana', models.CharField(blank=True, max_length=64, null=True)),
                ('telegram', models.CharField(blank=True, max_length=120, null=True)),
                ('twitter_x', models.CharField(blank=True, max_length=120, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('comment', models.TextField(blank=True, null=True)),
                ('wallet_used', models.CharField(blank=True, max_length=64, null=True)),
                ('post_url', models.URLField(blank=True, null=True)),
                ('visited_url', models.URLField(blank=True, null=True)),
                ('code_entered', models.CharField(blank=True, max_length=120, null=True)),
                ('proof_score', models.IntegerField(default=0)),
                ('rank_guess', models.IntegerField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.walletuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USDT', max_length=24)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('tx_hash', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent')], default='QUEUED', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('is_used', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.walletuser')),
            ],
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['campaign', 'status'], name='core_submis_campaig_438f60_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user'], name='core_submis_user_id_93bc43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('campaign', 'user')},
        ),
        migrations.AddIndex(
            model_name='campaigncode',
            index=models.Index(fields=['campaign', 'is_used', 'code'], name='core_campai_campaig_1f4b01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncode',
            unique_together={('campaign', 'code')},
        ),
    ]
