# Generated by Django 5.2.6 on 2025-10-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='visit_code',
            field=models.CharField(blank=True, help_text='The verification code users must enter for VISIT tasks', max_length=64),
        ),
    ]
