# Generated by Django 5.2.6 on 2025-10-14 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_campaign_visit_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("thumb_src", models.TextField(blank=True, null=True)),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ko", "Korean"),
                            ("ja", "Japanese"),
                            ("zh", "Chinese"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-posted_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "lang", "posted_at"],
                        name="core_event_is_publ_d488a8_idx",
                    )
                ],
            },
        ),
    ]
